import Link from "next/link";
import React from "react";

export default function Page() {
  return (
    <div>
      <Link href={`/podcast`}>
        <a>Podcast</a>
      </Link>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
      <div>hogehgoe</div>
    </div>
  );
}
